updated to golang latest version
chef/omnitruck-service pull request #60
Opened 2024-07-12 09:59 UTC by vviveksharma

## Description

- Added the latest golang version changes 
## Related Issue

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] If `Gemfile.lock` has changed, I have used `--conservative` to do it and included the full output in the Description above.
- [ ] All new and existing tests passed.
- [ ] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

2024-07-15 06:09 UTC, shanmugapriya-tr requested changes
Replace 22.4 across repository. PR doesn't have Dockerfile and sonar file changes

2024-07-22 06:15 UTC, vipin230 approved these changes

2024-07-25 05:57 UTC, ayush-billore commented
@vviveksharma  Sonar pipeline is failing. Please check

2024-07-25 07:35 UTC, RajeshPaul38 approved these changes

2024-07-25 07:50 UTC, vviveksharma commented
> @vviveksharma Sonar pipeline is failing. Please check

I have re-ran build multiple times but its still failing

2024-07-25 08:46 UTC, rishabhjhs approved these changes

2024-07-25 12:42 UTC, shanmugapriya-tr approved these changes

2024-07-25 14:27 UTC, sandhi18 approved these changes

2024-07-25 15:08 UTC, merged